# Generated by Django 2.2.6 on 2019-10-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
