# Generated by Django 2.2.6 on 2019-11-18 11:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191022_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30, verbose_name='Site Name or Logo')),
                ('back_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=50, verbose_name='Adress')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('linkedin', models.CharField(max_length=30, null=True, verbose_name='Linkedin')),
                ('github', models.CharField(max_length=30, null=True, verbose_name='Github')),
                ('twitter', models.CharField(max_length=70, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(max_length=70, null=True, verbose_name='Facebook')),
                ('insta', models.CharField(max_length=70, null=True, verbose_name='İnstagram')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Write Title')),
                ('description', ckeditor.fields.RichTextField(max_length=1800, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
